#pragma once

#include <Arduino.h>

const char HTML_FILE[] PROGMEM =
"<!doctype html>\n"
"<html lang=\"en\">\n"
"\n"
"<head>\n"
"  <!-- Required meta tags -->\n"
"  <meta charset=\"utf-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"  <!-- Bootstrap CSS -->\n"
"  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\n"
"    integrity=\"sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1\" crossorigin=\"anonymous\">\n"
"\n"
"  <title>Model Railroad Logs</title>\n"
"</head>\n"
"\n"
"<body class=\"d-flex flex-column min-vh-100\">\n"
"  <main class=\"flex-shrink-0\">\n"
"    <h1>Model Railroad Logs</h1>\n"
"    <table class=\"table table-striped table-hover\" id=\"log-table\">\n"
"        <tr class=\"table-primary sticky-top\">\n"
"          <th scope=\"col\">#</th>\n"
"          <th scope=\"col\">Timestamp</th>\n"
"          <th scope=\"col\">Level</th>\n"
"          <th scope=\"col\">Message</th>\n"
"        </tr>\n"
"    </table>\n"
"  </main>\n"
"  <footer class=\"footer mt-auto\">\n"
"    <div class=\"d-flex bg-success py-2\">\n"
"      <div class=\"form-check d-inline-flex flex-fill align-self-center mx-3\">\n"
"        <input class=\"form-control form-check-input\" type=\"checkbox\" checked=\"true\" id=\"checkBoxAutoScroll\">\n"
"        <label class=\"form-check-label\" for=\"checkBoxAutoScroll\">Auto Scroll to Bottom.</label>\n"
"      </div>\n"
"      <div class=\"form-group d-inline-flex align-self-center mx-3\">\n"
"        <button type=\"submit\" class=\"btn btn-primary\" id=\"buttonClear\">Clear</button>\n"
"      </div>\n"
"      <div class=\"form-group d-inline-flex align-self-center mx-3\">\n"
"        <button type=\"submit\" class=\"btn btn-primary\" id=\"buttonSaveToFile\">Save To File</button>\n"
"      </div>\n"
"    </div>\n"
"  </footer>\n"
"  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js\"\n"
"    integrity=\"sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW\"\n"
"    crossorigin=\"anonymous\"></script>\n"
"  <script type=\"text/javascript\">\n"
"    \"use strict\";\n"
"\n"
"    var lineNumber = 1;\n"
"    var shouldAutoScroll = true;\n"
"\n"
"    function appendToTable(rowNumber, timestamp, message_level, message) {\n"
"      let table = document.getElementById(\"log-table\");\n"
"      let row = table.insertRow();\n"
"      let num = document.createElement(\"th\");\n"
"      row.appendChild(num);\n"
"      let time = row.insertCell();\n"
"      let level = row.insertCell();\n"
"      let msg = row.insertCell();\n"
"      num.innerHTML = rowNumber;\n"
"      time.innerHTML = timestamp;\n"
"      level.innerHTML = message_level;\n"
"      msg.innerHTML = message;\n"
"    }\n"
"\n"
"    function download(data, filename, type) {\n"
"      var file = new Blob([data], { type: type });\n"
"      if (window.navigator.msSaveOrOpenBlob) // IE10+\n"
"        window.navigator.msSaveOrOpenBlob(file, filename);\n"
"      else { // Others\n"
"        var a = document.createElement(\"a\"),\n"
"          url = URL.createObjectURL(file);\n"
"        a.href = url;\n"
"        a.download = filename;\n"
"        document.body.appendChild(a);\n"
"        a.click();\n"
"        setTimeout(function () {\n"
"          document.body.removeChild(a);\n"
"          window.URL.revokeObjectURL(url);\n"
"        }, 0);\n"
"      }\n"
"    }\n"
"\n"
"    function getDataFromTable() {\n"
"      let data = \"\";\n"
"\n"
"      const table = document.getElementById(\"log-table\");\n"
"      const rowLength = table.rows.length;\n"
"      for (let i = 0; i < rowLength; i++) {\n"
"        const cells = table.rows.item(i).cells;\n"
"        const cellLength = cells.length;\n"
"        for (let j = 0; j < cellLength; j++) {\n"
"          const cellVal = cells.item(j).innerHTML;\n"
"          data += cellVal + ';';\n"
"        }\n"
"        data = data.replace(/;$/, '\\n');\n"
"      }\n"
"      return data;\n"
"    }\n"
"\n"
"    function saveToFile() {\n"
"      const now = new Date().toISOString().replaceAll(/[: ]/g, '-').slice(0, 19);\n"
"      const data = getDataFromTable();\n"
"\n"
"      download(data, \"log-model-raidroad-panel-\" + now + \".csv\", \"text/csv\");\n"
"    }\n"
"\n"
"    function parseData(text) {\n"
"      const lines = text.split('\\n');\n"
"      const parsed_lines = lines.filter(x => x !== \"\").map(x => x.split(/^ *(\\d+) ([FEWNTV]): (.*)$/));\n"
"      parsed_lines.forEach(x => appendToTable(lineNumber++, x[1], x[2], x[3]));\n"
"      if (shouldAutoScroll) {\n"
"        window.scrollTo(0, document.body.scrollHeight);\n"
"      }\n"
"    }\n"
"\n"
"    function refreshData() {\n"
"       const theUrl = \"update\";\n"
"      let xmlHttp = new XMLHttpRequest();\n"
"      xmlHttp.onreadystatechange = function () {\n"
"        if (xmlHttp.readyState == 4 && xmlHttp.status == 200)\n"
"          parseData(xmlHttp.responseText);\n"
"      }\n"
"      xmlHttp.open(\"GET\", theUrl, true);\n"
"      xmlHttp.send(null);\n"
"\n"
"      setTimeout(refreshData, 80);\n"
"    }\n"
"\n"
"    function init() {\n"
"      let autoScroller = document.getElementById(\"checkBoxAutoScroll\");\n"
"      autoScroller.addEventListener('change', function () { shouldAutoScroll = this.checked; });\n"
"      let fileSelect = document.getElementById(\"buttonSaveToFile\");\n"
"      fileSelect.addEventListener('click', saveToFile);\n"
"      let clearer = document.getElementById(\"buttonClear\");\n"
"      clearer.addEventListener('click', function() {\n"
"        let table = document.getElementById(\"log-table\");\n"
"        for (let i = table.rows.length - 1; i > 0; --i)\n"
"        {\n"
"          table.deleteRow(i);\n"
"        }\n"
"        lineNumber = 1;\n"
"      })\n"
"    }\n"
"\n"
"    init();\n"
"    refreshData();\n"
"  </script>\n"
"</body>\n"
"\n"
"</html>\n";
